In [11]:
import numpy as np
from sklearn.svm import SVC

# Clase que representa una muestra de aire
class AirSample:
    def __init__(self, pm25, pm10, o3, no2, quality=None):
        self.pm25 = pm25
        self.pm10 = pm10
        self.o3 = o3
        self.no2 = no2
        self.quality = quality  # 0 = saludable, 1 = contaminado

    def to_vector(self):
        return [self.pm25, self.pm10, self.o3, self.no2]


# Generador de datos sintéticos
class AirDataGenerator:
    def __init__(self, num_samples=200):
        self.num_samples = num_samples

    def generate(self):
        np.random.seed(42)  # Para reproducibilidad
        samples = []
        
        for _ in range(self.num_samples):
            pm25 = np.random.uniform(5, 100)
            pm10 = np.random.uniform(10, 150)
            o3 = np.random.uniform(10, 100)
            no2 = np.random.uniform(5, 80)
            
            # Asignar calidad según las reglas
            if pm25 > 35 or pm10 > 50 or no2 > 40:
                quality = 1  # contaminado
            else:
                quality = 0  # saludable
            
            samples.append(AirSample(pm25, pm10, o3, no2, quality))
        
        return samples


# Clasificador con SVM
class AirQualityClassifier:
    def __init__(self):
        self.model = SVC()

    def fit(self, samples):
        # Convertir samples a vectores de características y etiquetas
        X = np.array([sample.to_vector() for sample in samples])
        y = np.array([sample.quality for sample in samples])
       
        print(X)
       
       
        self.model.fit(X, y)

    def predict(self, sample):
        # Convertir la muestra a vector y predecir
        X = np.array([sample.to_vector()])
        prediction = self.model.predict(X)
        return prediction[0]


# Ejemplo de uso
class AirQualityExample:
    def run(self):
        # Crear generador con 200 muestras
        generator = AirDataGenerator(num_samples=200)
        
        # Generar datos de entrenamiento
        training_data = generator.generate()
        
        # Crear y entrenar el clasificador
        classifier = AirQualityClassifier()
        classifier.fit(training_data)
        
        # Crear nueva muestra para predicción
        new_sample = AirSample(pm25=22, pm10=30, o3=50, no2=35)
        
        # Predecir calidad del aire
        prediction = classifier.predict(new_sample)
        
        # Mostrar resultados
        print("🌍 Muestra de aire:")
        print(f"PM2.5: {new_sample.pm25}, PM10: {new_sample.pm10}, O3: {new_sample.o3}, NO2: {new_sample.no2}")
        
        if prediction == 0:
            print("✅ Predicción de calidad: Saludable ✅")
        else:
            print("⚠️ Predicción de calidad: Contaminado ⚠️")


# Ejecutar ejemplo
example = AirQualityExample()
example.run()


[[ 40.58131129 143.1000029   75.87945476  49.89938631]
 [ 19.82177084  31.83923285  15.2275251   69.96321093]
 [ 62.10592612 109.13016089  11.85260449  77.74323891]
 [ 84.08205088  39.72747549  26.36424705  18.75533824]
 [ 33.90301308  83.46590043  48.87505168  26.84218551]
 [ 63.126025    29.52914049  36.29301837  32.47713825]
 [ 48.3266485  119.9246346   27.97064039  43.56758288]
 [ 61.27938404  16.50305778  64.67903667  17.78930928]
 [ 11.17990133 142.84397522  96.90688298  65.62980111]
 [ 33.93830807  23.67409596  71.58097239  38.01143703]
 [ 16.59363231  79.32476742  13.0949669   73.19903016]
 [ 29.58409825 102.75311981  38.05399685  44.00510159]
 [ 56.93747654  35.87962377  97.2626165   63.13496175]
 [ 94.25239945 135.27582906  63.81099809  74.14056763]
 [ 13.40678769  37.43760074  14.070456    29.39977481]
 [ 41.92434252  47.98886445  84.58637582  31.7564995 ]
 [ 31.68877842  85.97745164  22.68318025  65.16477356]
 [ 12.08231115 148.16417112  79.50202924  19.90367612]
 [  5.5246

NameError: name 'X' is not defined