In [24]:
import numpy as np
#crear array
#minimo 10, maximo 39
array=np.arange(10,40)
array
#convierte en matriz 2 dimensiones
#3 filas por 10 columna
matriz =np.reshape(array, (3, 10))
matriz
#muestra el elemento superior de la derecha
matriz[0,9]

np.int64(19)

In [48]:
#crea array  9 valores enteros aleatoreos entre 0 y 100
array=np.random.randint(0,100,9)
array
#convierte en matriz 2 dimensiones:  3 filas 3 columnas
matriz =np.reshape(array, (3, 3))
#muestra elementto esquina inferior dewrecha
print(matriz)
matriz[2, 2]


[[18 84  1]
 [76 96 59]
 [90  3 71]]


np.int64(71)

In [56]:
import numpy as np

def analizar_finanzas(ingresos, gastos):
    """
    Analiza las finanzas personales de un estudiante usando NumPy.
    
    Args:
        ingresos (list o np.array): Ingresos mensuales (12 elementos).
        gastos (list o np.array): Gastos mensuales (12 elementos).
        
    Returns:
        np.array: [total_ingresos, total_gastos, saldo_final]
    """
    # 1. Convertir las listas a arrays de NumPy para operaciones eficientes
    arr_ingresos = np.array(ingresos)
    arr_gastos = np.array(gastos)
    
    # 2. Calcular el total de ingresos y gastos usando np.sum()
    total_ingresos = np.sum(arr_ingresos)
    total_gastos = np.sum(arr_gastos)
    
    # 3. Calcular el saldo final
    saldo_final = total_ingresos - total_gastos
    
    # 4. Devolver los resultados en un array
    mi_arreglo= np.array([total_ingresos, total_gastos, saldo_final])
    if (mi_arreglo > 0).any():
        return(mi_arreglo)
    

# --- Ejemplo de uso ---
ingresos_anuales = [1500, 1600, 1700, 1650, 1800, 1900, 2000, 2100, 2200, 2300, 2400, 2500]
gastos_anuales = [1000, 1100, 1200, 1150, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000]

resultado = analizar_finanzas(ingresos_anuales, gastos_anuales)

print(resultado)
# Salida esperada: [24250 17650  6000]


[23650 17650  6000]
