In [4]:
#array 2 dimensiones
import numpy as np

array=np.array( [[1,2,3], [4,5,6], [7,8,9] ])

array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array[0]

array([1, 2, 3])

In [6]:
array[0,1]

np.int64(2)

In [8]:
array[0][1]

np.int64(2)

In [7]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array[:, 0]
#de  todas las filas la columna 0

array([1, 4, 7])

In [12]:
array[:,:2]
#de  todas las filas la columna  2 elementos

array([[1, 2],
       [4, 5],
       [7, 8]])