In [5]:
import numpy as np
array=np.arange(0,10)

array

condicion=array>5

condicion



array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [7]:
array[condicion]

array([6, 7, 8, 9])

In [8]:
array[array>5]

array([6, 7, 8, 9])

In [10]:
array[array % 2 ==0]

array([0, 2, 4, 6, 8])