In [1]:
import numpy as np


In [9]:
array=np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#sumar entre si mismo
array+array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
#multiplicar por 100
array*100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [6]:
array-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [7]:
array  /  2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [10]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])