In [2]:
#install numpy
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 6.5 MB/s eta 0:00:000m eta 0:00:010:01:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
lista =[1,2,3,4]


array=np.array(lista)
array

array([1, 2, 3, 4])

In [6]:
lista2=[(1,2,3), (1,2,3), (1,2,3)]
array2=np.array(lista2)

array2



array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [14]:
import numpy as np
 

array = np.arange(5)
 
array


array([0, 1, 2, 3, 4])

In [15]:
#de 2 10 de un array
import numpy as np
 

array = np.arange(2,10 )
 
array

array([2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#de 2 en 2
import numpy as np
 

array = np.arange(2,10 ,2)
 
array

array([2, 4, 6, 8])

In [17]:
#genera array 1 dimension
np.zeros(3)


array([0., 0., 0.])

In [19]:
np.zeros((3,3))
#2 dimensiones


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.linspace(5,8,50)
#primer elemento 5 
#segundo elemento 8
#son 50 pasos para llegar al 8

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [22]:
np.eye(5)
#genera matriz de 2 dimensiones


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(2)
#genera matriz de 2 dimensiones


array([[1., 0.],
       [0., 1.]])

In [27]:
np.random.rand(5)#genera numeros aleatorios


array([0.96575598, 0.81434981, 0.75633939, 0.7291471 , 0.29563931])

In [29]:
np.random.rand(5,5)#genera numeros aleatorios 2 dimensiones

array([[0.13812765, 0.71102814, 0.5830618 , 0.37567634, 0.45629971],
       [0.63917607, 0.81156515, 0.34598245, 0.71829301, 0.99582026],
       [0.75624767, 0.21629544, 0.924412  , 0.51388563, 0.05453016],
       [0.3509216 , 0.49084844, 0.80905634, 0.61502204, 0.45158669],
       [0.33467562, 0.98930253, 0.19954863, 0.70555469, 0.16114897]])

In [30]:
np.random.randn(6)

array([-0.81015672, -1.11910088,  0.00175493,  0.93662005, -1.0936101 ,
       -1.10860374])

In [31]:
np.random.randn(6,2)

array([[ 0.53500537, -0.21605875],
       [ 0.41719146,  0.24704733],
       [ 2.76273343,  0.09740136],
       [ 0.58869938,  0.38871096],
       [ 0.90084133,  0.48514931],
       [ 0.77936724,  1.28062352]])

In [34]:
np.random.randint(1,10)
#genera entero aleatorio

6

In [36]:
np.random.randint(1,10,5)
#5 genera entero aleatorio

array([5, 3, 9, 5, 4])

In [40]:
array =np.random.randint(1,100,25)

array


matriz= array.reshape(5,5)
matriz
#la matriz debe coincidir con el numero de elementos

array([[84,  5, 76, 18,  3],
       [76, 65, 70, 68, 62],
       [12, 74, 44, 62, 65],
       [77, 30, 14, 99, 77],
       [73, 23,  2,  9, 11]])

In [60]:
array = np.random.randint(1, 100, 50)
print(array)
maximo=array.max()
minimo=array.min()
posicion=array.argmax()
posicionmin=array.argmin()
print("valor maximo " +format(maximo)  + " posicion "+ format(posicion) + " minimo " + format(minimo) + " posicion "+format(posicionmin))

[ 6 35 79 41 88 71 63 76 13 30 88 73 66 26  9 16 30 73  3 49 49 18 13 17
 77 78 27 36  3 59 62 50 44 73 25 43 49 80 92  2  5  3 51 13 37 33 16 56
 84 62]
valor maximo 92 posicion 38 minimo 2 posicion 39


In [69]:
array=np.arange(0,10)
array
array[0]
array[-1]
array[0:4]
array[9]

np.int64(9)

In [71]:
array=np.arange(0,10)
array2=array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])